export type Section = {
  id: string;
  name: string;
  kanji: string;
  kanjiElements: string[];
  completedCard: number;
  totalCards: number;
};

export const SECTIONS = {
  N5: [
    {
      id: "N5-S1",
      name: "Numbers & Counting",
      kanjiIds: [
        "一",
        "二",
        "三",
        "四",
        "五",
        "六",
        "七",
        "八",
        "九",
        "十",
        "百",
        "千",
        "万",
        "円",
      ],
      totalKanji: 14,
    },
    {
      id: "N5-S2",
      name: "Time & Dates",
      kanjiIds: [
        "日",
        "月",
        "年",
        "週",
        "時",
        "分",
        "午",
        "前",
        "後",
        "今",
        "先",
        "来",
        "毎",
        "半",
        "何",
      ],
      totalKanji: 15,
    },
    {
      id: "N5-S3",
      name: "Nature & Elements",
      kanjiIds: [
        "火",
        "水",
        "木",
        "金",
        "土",
        "山",
        "川",
        "田",
        "天",
        "空",
        "雨",
        "花",
        "気",
        "魚",
      ],
      totalKanji: 14,
    },
    {
      id: "N5-S4",
      name: "People & Directions",
      kanjiIds: [
        "人",
        "子",
        "女",
        "男",
        "父",
        "母",
        "友",
        "名",
        "上",
        "下",
        "左",
        "右",
        "中",
        "北",
        "南",
        "東",
        "西",
        "外",
        "間",
      ],
      totalKanji: 19,
    },
    {
      id: "N5-S5",
      name: "Places & School",
      kanjiIds: [
        "学",
        "校",
        "先",
        "生",
        "本",
        "語",
        "国",
        "社",
        "店",
        "駅",
        "道",
        "大",
        "小",
        "高",
        "安",
      ],
      totalKanji: 15,
    },
    {
      id: "N5-S6",
      name: "Body & Adjectives",
      kanjiIds: [
        "目",
        "耳",
        "口",
        "手",
        "足",
        "見",
        "聞",
        "白",
        "長",
        "新",
        "古",
        "多",
        "少",
      ],
      totalKanji: 13,
    },
    {
      id: "N5-S7",
      name: "Daily Verbs & Travel",
      kanjiIds: [
        "行",
        "来",
        "出",
        "入",
        "食",
        "飲",
        "書",
        "読",
        "言",
        "話",
        "売",
        "買",
        "休",
        "立",
        "車",
        "電",
      ],
      totalKanji: 16,
    },
  ],
};
